<a href="https://colab.research.google.com/github/Anubrata-Mallick/-Data-Preprocessing/blob/main/Handeling_Imbalanced_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imbalanced Data Set

A data set with an un equal class distribution

In [1]:
import pandas as pd
import numpy as np

In [2]:
credit_card_data = pd.read_csv("/content/credit_data.csv")

In [3]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
# distributionof 2 classes
credit_card_data['Class'].value_counts()

Class
0.0    71218
1.0      177
Name: count, dtype: int64

**This is a Highly Imbalanced Data**


0 --> Legit Transaction

1 --> Fraudulent Transaction

In [5]:
# separating the legit and fraudulent transactions
legit = credit_card_data[credit_card_data.Class == 0.0]
fraud = credit_card_data[credit_card_data.Class == 1.0]

In [6]:
print(legit.shape)
print(fraud.shape)

(71218, 31)
(177, 31)

Undr-sampling

Build a sample dataset containing similar distribution of Legit & Fraudulent Transactions


Number of fraud = 177

In [7]:
legit_sample = legit.sample(n=177)
print(legit_sample.shape)

(177, 31)

Concatinate 2 Data Frame

In [8]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
53786,46146,1.574577,-1.082330,-1.471941,-2.521649,1.256498,3.007030,-1.120807,0.647984,-2.266185,...,-0.612120,-1.608224,0.165296,0.930257,0.393475,-0.514151,0.010184,0.014339,23.84,0.0
5534,5618,-8.053149,7.045990,-1.102994,-0.870690,-1.360528,4.754590,-7.669995,-23.464595,3.056101,...,22.565680,-8.420246,3.511462,-0.526480,0.276928,0.207147,1.180975,0.194628,5.49,0.0
2985,2536,1.296669,0.421663,0.104537,0.555953,-0.011981,-0.740134,0.147811,-0.230904,-0.095063,...,-0.310994,-0.839449,0.050666,-0.163389,0.324909,0.124198,-0.016506,0.027550,0.89,0.0
63919,50927,-2.477184,0.860613,1.441850,1.051019,-1.856621,2.078384,0.510828,-0.243399,-0.260691,...,0.810408,0.692245,0.150121,-0.260777,0.005183,-0.177847,-0.510060,-0.660533,308.00,0.0
1752,1355,-1.724928,1.877471,0.433237,-1.002962,-0.059030,-0.524865,0.385128,0.434745,0.547897,...,-0.315927,-0.577281,-0.104841,-0.422631,0.146025,0.362496,0.598675,0.355718,1.00,0.0

In [9]:
new_dataset['Class'].value_counts()

Class
0.0    177
1.0    177
Name: count, dtype: int64